### ISSUE TITLE
How to add dependency to Gradle?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Chainfire/libsuperuser#27]
Just a tiny question for this great library please:

How do I add the dependency of this library to Android-Studio? What exactly should I do?

**Comment by Chainfire** [comment]
@afollestad I have actually started migrating to Android Studio today. A lot of what I'm doing is still Chinese, but I have looked shortly at uploading to jCenter. If you have some pointers, a good how-to, etc, it'd be most welcome as so far I'm not getting anywhere.

**Comment by afollestad** [comment]
@Chainfire nice! Well if you're familiar with Maven, you can put it on Maven Central instead of jCenter. Android Studio allows you to explicitly use Maven Central in addition to jCenter too. But jCenter is easier since it's there by default.

For jCenter, you just create a Maven repository on Bintray (https://bintray.com/), once you deploy your files you can add the repo to jCenter.

**Comment by Chainfire** [comment]
I'm not familiar with Maven Central or jCenter. I did create a jCenter account. But I don't know what the steps are. I think (a) turn it into a Maven artifact and (b) publish that to jCenter - but I can't find any docs or examples on how to do this easily. It's seem all the things I can find use intermediate build systems/repos. How hard can this be?

**Comment by AndroidDeveloperLB** [comment]
@Chainfire Hey I'm a huge newb in this too. Can you please share your findings?

**Comment by Chainfire** [comment]
Done.

For the dependency ( @afollestad ), see https://github.com/Chainfire/libsuperuser/blob/master/README.md

For the changes to get this working ( @AndroidDeveloperLB ) see
https://github.com/Chainfire/libsuperuser/commit/ec7f84c24400747f28921038ab86b2aa84b32e99

**Comment by afollestad** [comment]
@Chainfire awesome, thank you!

**Comment by AndroidDeveloperLB** [comment]
@Chainfire Seems like a lot. Did you copy it from some existing/general projects?
How long did it take?

**Comment by Chainfire** [comment]
I couldn't find a decent guide or example anywhere. So I first rolled my own which was significantly longer and didn't work as well. Then I ran into someone on IRC that gave me his script, and I adapted that.

**Comment by AndroidDeveloperLB** [comment]
@Chainfire I see. Thanks anyway. 
So, now in order to add the dependency, I need to add this:
    compile 'eu.chainfire:libsuperuser:201501111220'

?
It's a bit odd number. I've never seen such a format for dependency (of course, I've seen this format before, but not on Gradle) . 
What if I want to add "*" , so that it will auto-update?

**Comment by Chainfire** [comment]
The version number just identifies the minute it was built. libsuperuser has no real version number. Saves me the trouble of producing version numbers.

Anyway, I've prefixed it with '1.0.0', so now you can do:

dependencies {
    compile 'eu.chainfire:libsuperuser:1.0.0.+'
}

That should work how you want it, no?

**Comment by AndroidDeveloperLB** [comment]
Yes, thank you again. You are the best!

**Comment by MaxChinni** [comment]
I'm sorry, but I cannot find the lib under the maven repo.
Using the instruction in the [README.md](https://github.com/Chainfire/libsuperuser/blob/master/README.md) I get

    > Could not find any matches for eu.chainfire:libsuperuser:1.0.0.+ as no versions of eu.chainfire:libsuperuser are available.
      Searched in the following locations:
          https://repo1.maven.org/maven2/eu/chainfire/libsuperuser/maven-metadata.xml
          https://repo1.maven.org/maven2/eu/chainfire/libsuperuser/

Is the maven repo still active?

**Comment by MaxChinni** [comment]
Using jcenter "fixed" the problem.
Maybe could be useful to add the note in the readme.
It should be sufficient to add jcenter to gradle repositories

    repositories {
        mavenCentral()
        jcenter()
    }
