### ISSUE TITLE
Shell session could not terminate or stop

### ISSUE THREAD

**Issue by liudonghua123** [Chainfire/libsuperuser#33]
I looked into the code, but could not find the functionality of terminate or stop a shell session whether it is a interactive shell or not.
This feature is important for executing some commands like "tcpdump -p -vv -s 0 -w /sdcard/network_traffic.pcap" or "ps".

**Comment by E3V3A** [comment]
This doesn't sound like an SU problem, but a shell or binary signal trapping problem. (Better if you look in the code for those binaries, and see if they change the signal handling on their own.) Also check your currently set shell traps with: `trap` or `trap -l`, and compare them to the signal table with `kill -l`. Also recall that you can use: `CTRL + \` to send `QUIT` signal.

**Comment by liudonghua123** [comment]
I know this, currently I could terminate shell session using ``` process.destory() ``` where ```process``` is created by ```Process process = Runtime.getRuntime().exec(shell, environment);```.
Now I am just looking for the right place and appropriate manner to implement this feature.

**Comment by d4rken** [comment]
I don't think .destroy() works on a process that launched su-shell. I know i had troubles with this previously.

**Comment by Dereekturd** [comment]
Did you get it right liudongha123?

**Comment by liudonghua123** [comment]
no, currently I couldn't find some perfect solution.

**Comment by Kurdenes21** [comment]
#33
