### ISSUE TITLE
Keep shell open but kill a command

### ISSUE THREAD

**Issue by jaredrummler** [Chainfire/libsuperuser#34]
The situation:
---

I am writing a file manager and I am using [`FileObserver`](http://developer.android.com/reference/android/os/FileObserver.html) to watch for any changes in the current directory. While browsing directories with no read access I am running [`inotifywait -m`](http://linux.die.net/man/1/inotifywait) in a root shell. 

The process runs forever. When a user navigates to another directory I am calling `shell.kill()` and then adding a new command (`inotifywait [OPTIONS] [FILE]`) to listen to the new working directory.

The issue/request/question:
---

When running a command that never terminates (like `logcat` or `inotifywait`) is there a way to stop that command and run another command without requesting root access again (starting a new shell process)? 

I don't want the SuperSU toast to popup every time I need to kill the process and add another command.

If it is of any help, here is my code: http://pastebin.com/kG9Cjd4D

**Comment by Chainfire** [comment]
There's no way to kill individual commands, as there's no way to send the signal (without opening a secondary shell).

You could have a secondary shell open (the entire time) and send kill commands through that.

Or you could start `inotifywait -m &` so the inotify process is run async, and you can issue the kill command through the primary shell.

It's just shell coding, be creative.

**Comment by jaredrummler** [comment]
Thanks for the feedback. I will play around with opening a secondary shell or just use the recursive flag for inotifywait. :)

**Comment by ronnie8743** [comment]
On Apr 1, 2015 7:59 AM, "Jared Rummler" <notifications@github.com> wrote:
>
> Thanks for the feedback. I will play around with opening a secondary
shell or just use the recursive flag for inotifywait. :)

**Comment by ronnie8743** [comment]
Thank you so so much
On Apr 1, 2015 7:59 AM, "Jared Rummler" <notifications@github.com> wrote:
>
> Thanks for the feedback. I will play around with opening a secondary
shell or just use the recursive flag for inotifywait. :)

**Comment by ronnie8743** [comment]
Thank yoi

**Comment by jaredrummler** [comment]
Okay, so I think killing the command in another shell is the way to go. However,  I am trying to find the best way to get the PID for the command.

I am getting the PID of the process using this static factory method I wrote:

```java
public static int getPid(Process process) {
    try {
        Class<?> ProcessImpl = process.getClass();
        Field field = ProcessImpl.getDeclaredField("pid");
        field.setAccessible(true);
        return field.getInt(process);
    } catch (NoSuchFieldException | IllegalAccessException | IllegalArgumentException e) {
        return -1;
    }
}
```

This returns the PID for the shell and not the command. Example: got `25396` and ran `ps | grep 25396`:

    u0_a153   25396 25366 3188   364   c0275ca8 b6f8bb68 S su

___
Do you know how I can get the PID of the command? I guess I can parse the output of `ps`. For example: running the following command gives me the PID I'm looking for:

```shell
ps | grep inotifywait
```
    root      25408 25404 3168   820   c0275ca8 b6ea4b68 S /data/data/com.jrummyapps.rootbrowser/files/inotifywait/armeabi-v7a/inotifywait

This approach is not desirable because multiple inotifywait processes could be running.

___
Do you know of a better approach to getting the PID for the command and not the shell?

**Comment by jaredrummler** [comment]
Got it working. You can close this.
