### ISSUE TITLE
China

### ISSUE THREAD

**Issue by xjswxdx** [Chainfire/libsuperuser#36]
zh-cn

**Comment by xjswxdx** [comment]
求帮助翻译中文

**Comment by unforgettableid** [comment]
Google Translate says that the original poster writes:  "Seek help translate Chinese".

Dear OP:

In English:  Sorry, you must speak English (en_US) here, or else we may not understand you and we may close the ticket.

In simplified Chinese:  Google Translate says:  谷歌翻译说：对不起，你必须说英语（en_US）在这里，否则我们可能不理解你，我们可以关闭的车票。

**Comment by unforgettableid** [comment]
Anyway, for someone to offer translation assistance to any open-source project, I suspect they must be able to speak at least passable English.
