### ISSUE TITLE
The size of List<String> returned from Shell.run() was incorrect

### ISSUE THREAD

**Issue by twinsec** [Chainfire/libsuperuser#38]
Sometimes it missed the last string output. It would be OK on version 1.0.0.20150423. Please fix it.

**Comment by Chainfire** [comment]
Do you have a reproducable example?

**Comment by komamura** [comment]
Unable to reproduce on version, tried multiple commands.

**Comment by Chainfire** [comment]
Is this with Shell.SH.run/Shell.SU.run/Shell.run, or Shell.Builder/Shell.Interactive?

**Comment by twinsec** [comment]
Here's the example:

```java
		String [] commands = new String[backupInfo.backupPathList.size()];
		for (int i = 0; i < backupInfo.backupPathList.size(); i++) {
			commands[i] = "ls -l " + backupInfo.backupPathList.get(i);
		}

		List<String> suResult = Shell.run("su", commands, null, false);
```

And, yes, the commands does not end with \n, and suResult only have size() - 1 results.

**Comment by Chainfire** [comment]
I still cannot reproduce this.

Using test commands such as "echo -n someInterestingString" for example, which performs an echo command without adding a newline, and I get all the results back fine.

Are you sure one of those paths just doesn't exist and that's why you're a line short?
