### ISSUE TITLE
run() does not return null on failure

### ISSUE THREAD

**Issue by nioncode** [Chainfire/libsuperuser#39]
```Shell.SU.run("echo foo > bar");``` always returns an empty list instead of ```null```, even if I decline the SuperSU request.
I'd like to present the user the most exact error message possible, so I'd like to know if the issue is because there was no su access or if the command failed.

Currently, I have to do a ```Shell.SU.available()``` check before issuing my command.

Device: Nexus 5x on Marshmallow.

**Comment by Chainfire** [comment]
There is no reliable way to know if access was denied or the command returned no output, without echo-ing something yourself first.

**Comment by nioncode** [comment]
The docs at http://su.chainfire.eu/ say otherwise.
> The SH variants are used for a non-root shell, where the SU variants are used for a root shell. These calls return a List<String> containing the output of the shell commands. If there was no output, the list is empty, but not null. The result is only null in case an error occured - including the user not granting your app su access. These are blocking calls. 

Please update them, if the call really does never return 'null'.

What is the best practice to check for a permission error, then?
Something like `Shell.SU.run("echo foo > bar && echo 0")`?

**Comment by Chainfire** [comment]
If read the few lines of code, you'll see it does indeed sometimes return null. Specifically, when an error has occurred.

On some su binaries it does generate null, on others it does not.

Using ``Shell.SU.available()`` to check root is generally considered a good idea. Or indeed, you can echo something first. But you still need to check for null either way.

**Comment by nioncode** [comment]
The issue with Shell.SU.available() is that this is effectively the same as executing a custom command and checking its output. Thus, there are 2 calls with possibly 2 requests to the user (if he does not use 'always allow') and even if there are not 2 popups, it will be twice as slow, resulting in a ~700ms response instead of a ~350ms response during my tests on my Nexus 5x.

Thus, I now just run my custom command and check if it has worked afterwards without making an additional SU call.

It should definitely be added to the docs that it is not guaranteed to return null on errors that are caused by denied su access.

**Comment by Chainfire** [comment]
If you want to use a single shell for all of this, use Shell.Builder / Shell.Interactive, that's what it's for.
