### ISSUE TITLE
Provide access to return codes when possible

### ISSUE THREAD

**Issue by haxwithaxe** [Chainfire/libsuperuser#40]
It would be enormously useful to have access to the return codes of commands even if it is not guaranteed for non-zero return codes.
something like gobblers or a callback handler would be great.

**Comment by haxwithaxe** [comment]
read through Shell.java and I see it would be hard to implement this without changing the return type :(

**Comment by Chainfire** [comment]
You can use Shell.Builder / Shell.Interactive and use an OnCommandResultListener to get exit codes.

If you're using Shell.run / Shell.SH.run / Shell.SU.run and want to continue doing so, you can use $? for exit codes:

```
List<String> output = Shell.SU.run(new String[] {
    "rm -rf /data/dalvik-cache/*",
    "echo return code was $?"
});
```

**Comment by haxwithaxe** [comment]
my apologies if it is already in the documentation somewhere but if you put the contents of your comment there into the docs it would be useful. that is exactly what i had been looking for.
thanks
