### ISSUE TITLE
Unable to cat ftrace buffer to a secondary user directory 

### ISSUE THREAD

**Issue by farleylai** [Chainfire/libsuperuser#41]
I'm playing with the ftrace on the Nexus 6 with Lollipop. Everything works as expected except saving the trace buffer "/d/tracing/trace" to the secondary user storage directory using the "cat" command as follows. The number 10 indicates the secondary user who logged in and the storage path is gotten from the Environment. The file may be created but the content is not written so the size is zero.

`cat /d/tracing/trace > /storage/emulated/10/Download/trace.log`

On the other hand, if it is the primary user, the same command works as expected and the trace buffer is fully written to the primary user's directory.

`cat /d/tracing/trace > /storage/emulated/0/Download/trace.log`

I'm wondering if there is something missing here. Any idea?

PS: both uses SU.

**Comment by Chainfire** [comment]
I'd guess it's an SELinux issue. Regardless, this has nothing at all to do with libsuperuser.
