### ISSUE TITLE
Binary stdout

### ISSUE THREAD

**Issue by JoelSjogren** [Chainfire/libsuperuser#42]
Currently all shell methods I know of look like
> List\<String> Shell.SH.run(String command)

in that they return a list of lines (excluding \n) of standard output. Surely, this shouldn't work for binary output: What if there are no newline characters, what if there are, what if there are value-zero characters, what if the current String encoding is UTF-16?

How does one get byte[] output instead?

**Comment by Chainfire** [comment]
There isn't currently any way to properly do that in libsuperuser.
