### ISSUE TITLE
maven package missing

### ISSUE THREAD

**Issue by kived** [Chainfire/libsuperuser#44]
This seems to no longer be available on Maven Central. Adding `compile 'eu.chainfire:libsuperuser:1.0.0+'` results in a `failed to find` error. Manually searching Maven Central via the dialog in Android Studio or via search.maven.org does not find any package either.

**Comment by d4rken** [comment]
https://bintray.com/chainfire/maven/libsuperuser

**Comment by dschuermann** [comment]
@kived besides mavenCentral(), you need jcenter() in your repostories in gradle.
