### ISSUE TITLE
end/exit marker processing

### ISSUE THREAD

**Issue by pedja1** [Chainfire/libsuperuser#45]
If command that was executed in a shell doesn't print new line on the end, detecting command exit will not work properly.

Correct me if im wrong, this is my understandin of libsuperuser after quick look over the code....

libsuperuser marks end of command by echoing random string to stdout and stderror, and then checks for those lines during output parsing. When marker is found that means that command was finished.

```java
STDIN.write(("echo " + command.marker + " $?\n").getBytes("UTF-8"));
STDIN.write(("echo " + command.marker + " >&2\n").getBytes("UTF-8"));
```

If last line on the actual command (command that user executed) is not new line (or doesnt end with new line (\n)), echos mentioned above will merge with last line of the actual output.
This is used to perform check if line is marker:

```java
if (line.startsWith(command.marker))
```

which in this case will be false, because marker will actualy be on the end of the line, not a new line.

Am i correct, and can someone suggest a workaround.
Will something like this work?

```java
STDIN.write(("echo \n" + command.marker + " $?\n").getBytes("UTF-8"));
STDIN.write(("echo \n" + command.marker + " >&2\n").getBytes("UTF-8"));
```

Just an example:
libsuperuser will never finish command from this program:

```c
int main(int argc, char **argv)
{
    printf("no new line at the end");
    return 0;
}
```

**Comment by Chainfire** [comment]
Related to #38 . This is a real issue, your suggested fix may work as a temporary work-around. Looking at a better way to fix it.

**Comment by d4rken** [comment]
My code is a bit different, but it's based on libsuperuser and I've got the same bug, funnily enough I never ran into this until yesterday (when doing cat on an xml file). The mentioned workaround above doesn't work like that for me.
This works:
``` bash
echo $'\n" + command.getMarker() + "' $?\n
echo $'\n" + command.getMarker() + "' >&2\n
```
The issue with the workaround is that in all non edge cases like this we get an extra empty line in our ouput.

Currently my solution is to check the index and if necessary split the output.
This is cleaner because it doesn't alter the output, but slightly worse in performance, because instead of just checking every line with ```String.startsWith(marker)``` we do a ```String.contains(marker)``` but I doubt that is noticeable. So inside the stream gobblers onNewLine method we have:
``` java
public void onNewLine(@NonNull String line) {
     synchronized (InteractiveShell.this) {
         if (mCommand == null)
             return;
         int markerIndex = line.indexOf(mCommand.getMarker());
         if (markerIndex != -1) { // Line contains a marker
             if (markerIndex > 0) { // We have hit the edge case, split off output.
                 String clingyOutput = line.substring(0, markerIndex);
                 addBufferOutput(clingyOutput);
                 processLine(clingyOutput, mGlobalOutputListener); 
             }
             try {
                 int exitCodeIndex = markerIndex + mCommand.getMarker().length() + 1; // Adjust exitcode position for edge case if necessary
                 mLastExitCode = Integer.valueOf(line.substring(exitCodeIndex, exitCodeIndex + 1));
             } catch (Exception e) {
                 Timber.tag(TAG).e(e, null);
                 Bugsnag.notify(e);
             }
             mLastMarkerOutput = mCommand.getMarker();
             processMarker();
         } else {
             addBufferOutput(line);
             processLine(line, mGlobalOutputListener);
         }
     }
 }
```

@Chainfire If you want I can submit a PR with this change.
