### ISSUE TITLE
Gradle dependencies error

### ISSUE THREAD

**Issue by nickand** [Chainfire/libsuperuser#46]
Hi, the compile has changed in the gradle? because i use your library for listing my process in background and the library gives me this error:

Error:(38, 13) Failed to resolve: eu.chainfire:libsuperuser:1.0.0.+

By the way, your library is great Chainfire!

Cheers!

**Comment by DeepakSenapati** [comment]
I am getting this issue too now. 
Failed to resolve: eu.chainfire:libsuperuser:1.0.0.+
So the issue still exists
Could you please comment on it before closing the issue.
