### ISSUE TITLE
Gradle dependency error

### ISSUE THREAD

**Issue by silvara** [Chainfire/libsuperuser#47]
Until before few days ago, I successfully compiled this application with same codes.
But since today, when I tried to build the application in android studio, I found a gradle error.

`Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve eu.chainfire:libsuperuser:1.0.0.+.
     Required by:
         android-msnlcollector:app:unspecified
      > Could not resolve eu.chainfire:libsuperuser:1.0.0.201602232304.
         > inconsistent module metadata found. Descriptor: eu.chainfire:libsuperuser:1.0.0.201602232303 Errors: bad version: expected='1.0.0.201602232304' found='1.0.0.201602232303'`

**Comment by ReinhardStrauch** [comment]
same behavior here since today morning!

**Comment by monossido** [comment]
+1

**Comment by dwitherell** [comment]
I know little of such things, but if I had to guess I'd say it looks like the version in the 1.0.0.201602232304 pom file (located in https://jcenter.bintray.com/eu/chainfire/libsuperuser/1.0.0.201602232304/ ) is causing the issue as the version tag shows 1.0.0.201602232303

**Comment by ReinhardStrauch** [comment]
@dwitherell,

compile 'eu.chainfire:libsuperuser:1.0.0.201602011018' - as workaround does it! Thanx!

**Comment by Chainfire** [comment]
I uploaded a new version to bintray/jcenter, hope that fixes it (beware local caches)

**Comment by ReinhardStrauch** [comment]
@Chainfire,

the error persists after upload of new version :( ...

If you have a look into the folder structure of  https://jcenter.bintray.com/eu/chainfire/libsuperuser/
you can see the diffs in the newer folders - newer than 1.0.0.201602011018.  Seems there don't exist some necessary files?!

**Comment by Chainfire** [comment]
I think I fixed it, see https://jcenter.bintray.com/eu/chainfire/libsuperuser/1.0.0.201602242357/

Stupid plugins changing all the time breaking things...

**Comment by dwitherell** [comment]
@Chainfire seems to be happier on my end anyway - thanks for the quick fix :)

**Comment by silvara** [comment]
Thank you :+1:
