### ISSUE TITLE
Is it possible to send CTRL-C?

### ISSUE THREAD

**Issue by hendraanggrian** [Chainfire/libsuperuser#48]
I'm trying to execute [screenrecord](http://developer.android.com/tools/help/shell.html#screenrecord) and it seems that the only way to stop it is to send CTRL-C or simply wait for 3 min limit time. The worst part is while screenrecord is active, I cannot execute other commands until screenrecord process stops.

Is it possible to send CTRL-C to `Shell.SU.run()`? Or perhaps multiple threads of ADB Shell so I can use 1 for screenrecord and another for killing the process of screenrecord. You know, like when you have 2 windows on your Terminal.

Thank you.

**Comment by AndroidDeveloperLB** [comment]
Why do you use root for this? It can be managed via the API...

**Comment by d4rken** [comment]
AFAIK sending CTRL-C is not possible.

There are other approaches though:
You can open as many shells as you want.
You can also modify the timeout values.

Also as @AndroidDeveloperLB  mentioned there are API methods for taking pictures but this slightly depends on what you are trying to screenshot and API level you are aiming for.

**Comment by hendraanggrian** [comment]
@AndroidDeveloperLB yes, you may record screen at API-level using MediaProjection API. The thing is, it's 5.0 or newer. So I have to use `adb screenrecord` to support older version of Android.

**Comment by hendraanggrian** [comment]
@d4rken How do you open a new shell instance? I thought this library is supposed to be used with simple, single static instance like `Shell.SU.run(String command)`.

**Comment by AndroidDeveloperLB** [comment]
@hendraanggrian I think this way:


            final AtomicReference<Shell.Interactive> rootSessionRef = new AtomicReference<>();
            rootSessionRef.set(new Shell.Builder().useSU().setWantSTDERR(true).setWatchdogTimeout(5).setMinimalLogging(true).open(//
                    new Shell.OnCommandResultListener() {
                        @Override
                        public void onCommandResult(final int commandCode, final int exitCode, final List<String> output) {
                            final boolean success = exitCode == Shell.OnCommandResultListener.SHELL_RUNNING;
                            if (success)
                                _rootSession = rootSessionRef.get();
                        }
                    }));

When you get to "sucess", you can use "_rootSession" .

**Comment by FaridBeiranvand** [comment]
hi.i want to use 'adb shell screenrecord' command with this library.what is the right way for use it?and my device is not root.can i use Shell.SU.run() for this command?

**Comment by AndroidDeveloperLB** [comment]
@FaridBeiranvand  For new questions, please create a new thread.
As for the question, if your device isn't rooted, this library cannot be used on it. It requires root.
However, Android already has an official API for screen recording, so you should use it instead of going to root solutions:
http://stackoverflow.com/q/32513379/878126
