### ISSUE TITLE
Shell.Builder.open(Shell.OnCommandResultListener) doesn't work if user rejects SU request

### ISSUE THREAD

**Issue by Mygod** [Chainfire/libsuperuser#55]
[This](https://github.com/Chainfire/libsuperuser/commit/1428b2b7a9393035b70c71ed6073d88f92522878#diff-0242abc6b18aed69f1488b6c005b66f1R1413) should be `if (fCommand.onCommandResultListener != null)`.

@dschuermann

**Comment by dschuermann** [comment]
Make a pull request? :)

**Comment by Mygod** [comment]
This bug exists for almost 2 years. Is it that no one uses `Shell.Interactive` now?

**Comment by dschuermann** [comment]
I think nobody uses Shell without su access.

**Comment by Mygod** [comment]
Umm good point. But why request SU twice when you can request once?

**Comment by Chainfire** [comment]
The same change should be applied a few lines below ...

**Comment by Mygod** [comment]
@Chainfire Fixed. Thanks for pointing that out.
