### ISSUE TITLE
Updating to 1.0.0.201607041850 caused blocking issues

### ISSUE THREAD

**Issue by bagintz** [Chainfire/libsuperuser#63]
I was on 1.0.0.201602271131 and previous versions and everything worked great.  When it updated to 1.0.0.201607041850 I started getting complaints from users that things were taking forever to run (things that took root, basically just Shell.SU.available() and one Shell.SU.run().  When I put it back to 1.0.0.201602271131 it worked fine.  I would be happy to provide whatever information that would be helpful.

**Comment by Chainfire** [comment]
The version number is the date of release. If you can reproduce the issue, use the source from the old version, apply the patches from GitHub's commit history one by one (there are only a handful), and see when it starts breaking.

**Comment by Rgdelrosario91** [comment]
Nafication not work.

**Comment by panakron00001** [comment]
#63

**Comment by panakron00001** [comment]
#65

**Comment by greeneterran** [comment]
how to su
