### ISSUE TITLE
Shell.SU.run() does not always return command result

### ISSUE THREAD

**Issue by bamsbamx** [Chainfire/libsuperuser#66]
**Happening with:** Nexus 4 running Android Marshmallow with SuperSu installed and properly working. Dont know if happens with other Android versions or other devices (but I guess so).

**Steps to reproduce:** Running sample command 

    Shell.SU.run("pm revoke io.plaidapp android.permission.INTERNET");

will result in a empty String array, while running the same command through ADB Shell terminal (from the PC) will result in the following sentence '_Operation not allowed: java.lang.SecurityException: Can't change android.permission.INTERNET. It is required by the application_'

**Suggestion:** Either return null (because it throws _java.lang.SecurityException_) or return the whole message as a String

![capture](https://cloud.githubusercontent.com/assets/1826232/23794765/1bacc72c-0592-11e7-9b11-8186df1dda77.PNG)

**Comment by d4rken** [comment]
Where is the message printed, stdout or stderr?

Isn't the "result" being returned, i.e. `exitcode == 1`

**Comment by bamsbamx** [comment]
@d4rken 
I have noticed that if I call run with wantSTERR as true it indeed returns the same message as the ADB Shell:

Shell.run("su", new String[]{command}, null, true);

I dont know how to retrieve exixCode, though

**Comment by panakron00001** [comment]
#66

**Comment by panakron00001** [comment]
1
