### ISSUE TITLE
Paths to external app cache folder

### ISSUE THREAD

**Issue by dave08** [Chainfire/libsuperuser#72]
How do I get to the path of `Context.getExternalCacheDir()` using this shell? In the lib I was currently using (org.sufficientlysecure.rootcommands), I could just do (in Kotlin): `context.externalCacheDir.absolutePath.replace("/storage/emulated/0","\$EXTERNAL_STORAGE")` and it worked, with this lib it doesn't. Is there any difference? How could I accomplish the same thing across all device models?

**Comment by Chainfire** [comment]
That command doesn't seem related to root?

**Comment by WASIM88AHMED** [comment]
We hu

**Comment by lucasborer1** [comment]
@Chainfire

**Comment by lucasborer1** [comment]
@Chainfire

**Comment by dave08** [comment]
I thought it did apply since there seemed to be a difference between the libraries. But in the end it was my fault, since some devices have magisk that don't need -mm and older ones had your rooting that did require it. When I omitted -mm the cache dir wasn't visible to the root shell. Thanks for responding!
