### ISSUE TITLE
Question: How to stream from a given inputStream into a root-command outputStream?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Chainfire/libsuperuser#74]
It seems that sometimes, it's needed to stream data from an InputStream into the outputStream of a root command.

Example can be found on this repository (which demonstrates how to install split-apks using root) :
https://github.com/Aefyr/SAI

If you look at its`RootedSAIPackageInstaller.java` file, you can see it's calling this:

```
while (apkSource.nextApk())
     ensureCommandSucceeded(Root.exec(String.format("pm install-write -S %d %d \"%s\"", apkSource.getApkLength(), sessionId, apkSource.getApkName()), apkSource.openApkInputStream()));
```

And the code for its root class is as such:

```
    private static Result execInternal(String command, @Nullable InputStream inputPipe) {
        try {
            Process process = Runtime.getRuntime().exec(String.format("su -c %s", command));

            StringBuilder stdOutSb = new StringBuilder();
            StringBuilder stdErrSb = new StringBuilder();
            Thread stdOutD = writeStreamToStringBuilder(stdOutSb, process.getInputStream());
            Thread stdErrD = writeStreamToStringBuilder(stdErrSb, process.getErrorStream());

            if (inputPipe != null) {
                IOUtils.copyStream(inputPipe, process.getOutputStream());
                inputPipe.close();
                process.getOutputStream().close();
            }

            process.waitFor();
            stdOutD.join();
            stdErrD.join();

            return new Result(command, process.exitValue(), stdOutSb.toString().trim(), stdErrSb.toString().trim());
        } catch (Exception e) {
            Log.w(TAG, "Unable execute command: ");
            Log.w(TAG, e);
            return new Result(command, -1, "", "Java exception: " + Utils.throwableToString(e));
        }
    }
```

What is the equivalent for this on libsuperuser ?

**Comment by Chainfire** [comment]
There isn't one, currently.

**Comment by AndroidDeveloperLB** [comment]
I didn't know it's even possible. It seems it can be useful though:

http://www.longluo.me/blog/2016/10/01/Android-Develop-Tools-ADB-Manual/


> pm install-write: write a package into existing session; path may
>   be '-' to read from stdin
>     -S: size in bytes of package, required for stdin

That's probably what the repository is using.
Weird is that I don't see all commands on official docs though:
https://developer.android.com/studio/command-line/adb

**Comment by Chainfire** [comment]
This would be very tricky to get right for an interactive shell, due to all the edge-cases on how programs handle STDIN., and only very rarely used. If you must do this exact thing, use the sample code you provided yourself.

Think of a work-around? For this specific case there are several. For this install-write command you could just use the source paths of the APKs in the command directly instead of reading the APK into a stream and then writing it to another, for example. Or PIPE the commands on the shell level rather than the Java level.

If the data isn't coming from disk, you can cache it on disk and pass the path, or maybe even create a fifo file you write to from Java and read from in the shell.

**Comment by AndroidDeveloperLB** [comment]
Suppose I got root, though, this could still work later, no?
It won't ask the user for root again, right?

**Comment by Chainfire** [comment]
That depends on the root management app. They can be set to ask for every "su" request, in which case you'd be asked again. Mostly the default is ask once for any UID and then keep it granted, so you'd only see it once regardless of which method you use to execute root commands.

**Comment by AndroidDeveloperLB** [comment]
Thought so. 
Would you please reconsider adding this though? Even as a stand-alone function?
I think you got all the other cases covered, except this one.
