### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Chainfire/libsuperuser#75]
I get this:

![image](https://user-images.githubusercontent.com/5357526/61174380-d0a35f80-a5a7-11e9-84ab-2dee92133296.png)

Also, BTW, you can remove the "buildToolsVersion" part. It's not needed anymore, for a long time...

**Comment by AndroidDeveloperLB** [comment]
Removing this solved it:

```
task findConventions << {
    println project.getConvention()
}
```

**Comment by Chainfire** [comment]
Hmm, not sure why that is even there.

**Comment by AndroidDeveloperLB** [comment]
I don't even know what it's supposed to do. I just tried and it worked...
As for updating, usually the IDE whines about updating the gradle version, so I try to at least give it an update to the latest official one (not beta/alpha stuff).

**Comment by Chainfire** [comment]
No idea here either. Probably a left-over of debugging something. Next push will get rid of it.

**Comment by AndroidDeveloperLB** [comment]
Thank you.
You can also remove the "buildToolsVersion" . It's not needed anymore
