### ISSUE TITLE
Request: add threads annotations to functions

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Chainfire/libsuperuser#78]
Meaning:
`@UiThread`
`@WorkerThread`
`@AnyThread`

**Comment by Chainfire** [comment]
Don't have time for this right now, but feel free to create a pull request.

**Comment by AndroidDeveloperLB** [comment]
Sadly on most cases I'm not sure which is right.
I prefer not to put wrong stuff that you might miss.

**Comment by Chainfire** [comment]
Several methods are dependent on usage. They may work from the main thread, or they may not. Any idea on how those should be annotated (or not at all) ?

**Comment by AndroidDeveloperLB** [comment]
Well things that call linux commands should probably be in background thread, no?
That's because you don't know when they will finish...

As for the rest, it really depends.
If you have functions that can run on both, but depends on case, maybe you should mark them as running on background thread, or at least explain in which cases it's ok to use them on the UI thread, in the Java-docs of them.

**Comment by Chainfire** [comment]
Yes, the case is clear for things such as `addCommand` and `run`. (`@AnyThread` and `@WorkerThread` respectively). 

`closeImmediately` is fine from any thread *if* the shell is idle, but bad if it isn't. There are a couple of calls like that.

**Comment by AndroidDeveloperLB** [comment]
So for closeImmediately , you chose WorkerThread , or AnyThread  with docs about it?
I think that for worst cast, it's better to use WorkerThread , or if possible split it into 2 functions, that each has a different annotation.

The annotations help with avoiding possible bugs. I think that sometimes they are checked as you type.

**Comment by Chainfire** [comment]
I did go "worst case", so yes, `closeImmediately` gets `@WorkerThread`, though the javadoc says it can be called from the UI thread if the shell is already idle.

It seems they are checked as you type, but you can right-click on it to make an exception. If you know enough to know that `closeImmediately` *can* be called in a certain case, you probably also know enough to disable the error. And if not, it will push the user to use the safest option.

**Comment by AndroidDeveloperLB** [comment]
Yes I think it's the wisest thing to do in those cases.
Say, do the languages you work on also have similar stuff? I'm curious..

**Comment by Chainfire** [comment]
As mentioned in the other thread I'm doing a lot of C and Python now. C barely has any safety features, Python doesn't have nullity helpers and doesn't try to null-safe like Kotlin. It doesn't really do threading like other languages, so threading issues don't really exist.

**Comment by AndroidDeveloperLB** [comment]
I see. Thank you.
