### ISSUE TITLE
I want use this to build android-terminal

### ISSUE THREAD

**Issue by Nightmare-MYS** [Chainfire/libsuperuser#79]
I have to build terminal,and I tried a lot of libraries,
all of them have one question is cannot interact with the user,
the java file do have so much comments,i still not sure what the problem is.
some need interact with the usr commands,and hava no output.
```sh
read xxx
python
ssh
scp
```
but  I found some terminal from others can support this,whether this project can sovle this problem?some help,thanks.

**Comment by Chainfire** [comment]
Writing a terminal emulator is a very specific use-case, this library will not help you with that much.

This library will not help you with this.
