### ISSUE TITLE
Version problem？

### ISSUE THREAD

**Issue by fandeus** [Chainfire/libsuperuser#80]
hey guys
when i use 
`implementation 'eu.chainfire:libsuperuser:1.1.0.+'`
ide warning me this 
`Avoid using+ in version number`
i am look for your version number it‘s day number  that your reayl number 
eu.chainfire:libsuperuser:1.1.0.201907261845
chould you fix this？

**Comment by Chainfire** [comment]
If you want to get rid of the +, just use the full number. But you won't get the benefit (or problem) of automatic updates to the 1.1.0 branch.
